
using System.Text.Json.Serialization;

namespace FitSyncHub.IntervalsICU.HttpClients.Models.Common;

[JsonConverter(typeof(JsonStringEnumConverter<WellnessSportInfoType>))]
public enum WellnessSportInfoType
{
    Ride,
    Run,
    Swim,
    WeightTraining,
    Hike,
    Walk,
    AlpineSki,
    BackcountrySki,
    Badminton,
    Canoeing,
    Crossfit,
    EBikeRide,
    EMountainBikeRide,
    Elliptical,
    Golf,
    GravelRide,
    TrackRide,
    Handcycle,
    HighIntensityIntervalTraining,
    Hockey,
    IceSkate,
    InlineSkate,
    Kayaking,
    Kitesurf,
    MountainBikeRide,
    NordicSki,
    OpenWaterSwim,
    Padel,
    Pilates,
    Pickleball,
    Racquetball,
    Rugby,
    RockClimbing,
    RollerSki,
    Rowing,
    Sail,
    Skateboard,
    Snowboard,
    Snowshoe,
    Soccer,
    Squash,
    StairStepper,
    StandUpPaddling,
    Surfing,
    TableTennis,
    Tennis,
    TrailRun,
    Transition,
    Velomobile,
    VirtualRide,
    VirtualRow,
    VirtualRun,
    WaterSport,
    Wheelchair,
    Windsurf,
    Workout,
    Yoga,
    Other
}
