name: Build and deploy .NET Core application to Function App FitSyncHubFunctions
on:
  push:
    branches:
    - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: FitSyncHubFunctionsApp
  AZURE_FUNCTIONAPP_PACKAGE_PATH: src/FitSyncHub.Functions/published
  CONFIGURATION: Release
  DOTNET_VERSION: 9.0.x
  WORKING_DIRECTORY: src/FitSyncHub.Functions
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        sku: 'flexconsumption'    # Parameter required when using a publish profile with Flex Consumption
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
